Update getting-started.md
alire-project/alire pull request #1000
Opened 2022-04-21 16:26 UTC by Fabien-Chouteau

2022-04-21 17:01 UTC, simonjwright commented
(1) Line 8 shouldn’t mention macOS.

(2) On macOS, there’s an issue with System Integrity Protection: the `alr` binary is quarantined,
```
$ xattr -v bin/alr 
bin/alr: com.apple.quarantine
```
If you try to run it on recent versions of macOS, you’ll get a popup saying '“alr” cannot be opened because the developer cannot be verified.' and inviting you to move it to the bin.

The way round this is to remove the quarantine attribute,
```
$ xattr -d com.apple.quarantine bin/alr
```

2022-04-21 19:48 UTC, mosteo requested changes
Just a typo.

Also adding the info provided by Simon looks useful for macOS.

2022-04-21 19:48 UTC, mosteo commented on doc/getting-started.md
> +the option look at the GNAT toolchains from the community.
option [to] look

2022-04-22 13:10 UTC, Fabien-Chouteau commented
Thanks both :+1:

2022-04-22 14:38 UTC, mosteo approved these changes

2022-04-22 14:38 UTC, merged