Add source code recommendations to the policies
alire-project/alire pull request #1202
Opened 2022-10-01 12:22 UTC by reznikmm

about UTF-8 encoding and a URL to Ada Style Guide. Refs #919.

2022-10-03 09:00 UTC, Fabien-Chouteau approved these changes

2022-10-03 12:40 UTC, mosteo requested changes

2022-10-03 12:40 UTC, mosteo commented on doc/policies.md
> + - Consider to follow or at least familiarize your-self with the
Just a couple of menor editions:

- Replace "ok" with "OK".
- Replace "your-self" with "yourself".

2022-10-05 09:35 UTC, mosteo approved these changes

2022-10-05 09:35 UTC, mosteo commented
Thanks Maxim, merging now.

2022-10-05 09:35 UTC, merged