Actually use the cache location for shared releases
alire-project/alire pull request #1349
Opened 2023-03-14 18:50 UTC by mosteo

We fixed the cache path in #1265 but the deployer of binary releases was defaulting to the config location.

2023-03-15 16:00 UTC, Fabien-Chouteau approved these changes
This might be worth adding a test.

2023-03-16 08:44 UTC, mosteo commented
I thought about it, but all of our tests are running with custom config to avoid getting contaminated by the user config. So in a way it's being tested, but the default isn't.

I can't think an easy way of running a test with default environment short of using something like chroot... Do you have any ideas?

2023-03-16 09:04 UTC, Fabien-Chouteau commented
I forgot about the custom config for the testsuite. I don't have a solution to offer...

2023-03-20 11:27 UTC, mosteo commented
I've got a solution for testing with default config but that will be in a separate PR as it's not trivial. 

In this one I've added a migration assistant to try and save some large downloads to people. It runs only once even if it fails, as the worst thing that can happen is that you need to redownload compilers to the new location, so I prefer not to risk it interfering unexpectedly.

2023-03-21 10:50 UTC, Fabien-Chouteau requested changes

2023-03-21 10:50 UTC, Fabien-Chouteau commented on src/alire/alire-toolchains-solutions.adb
> +   procedure Migrate_Cache is
I don't like having such a big piece of code for something that only has to be done once. Downloading dependencies is not that bad of an issue.

2023-03-21 11:23 UTC, Fabien-Chouteau approved these changes

2023-03-21 11:26 UTC, merged