Debug when folder deletion fails
alire-project/alire pull request #1426
Opened 2023-08-07 19:04 UTC by mosteo

Extra output when a file/folder deletion fails, to try and debug occurrences like #1417.

2023-08-09 16:56 UTC, Fabien-Chouteau requested changes

2023-08-09 16:56 UTC, Fabien-Chouteau commented on src/alire/alire-directories.adb
> +                       ("ls", To_Vector ("-alRF"),
I don't think it's good to rely on and external `ls` command here. On Windows it might not be available.

2023-08-21 16:04 UTC, mosteo commented
I've added an alternative for Windows. Nonetheless, this is kind of a brute attempt to diagnose exactly the failures happening here... Other ideas welcome :S

2023-08-22 06:12 UTC, mosteo commented
I know what the root cause is now and can reproduce locally, working on the fix.

2023-08-22 16:21 UTC, mosteo commented
The CI error in this one will go away after #1427

2023-08-24 12:27 UTC, Fabien-Chouteau approved these changes

2023-08-24 12:34 UTC, merged