Improve VSCode launch command
alire-project/alire pull request #1703
Opened 2024-06-18 11:27 UTC by mosteo

Fixes #1692, per discussion therein.

2024-06-18 12:42 UTC, Fabien-Chouteau requested changes

2024-06-18 12:42 UTC, Fabien-Chouteau commented on src/alr/alr-commands-edit.adb
> +   Root_Pattern  : constant String := "${CRATE_ROOT}";
I think we have two places where we do this kind of replacement. We will have to make a proper package to handle variable replacement at some point.

2024-06-18 12:42 UTC, Fabien-Chouteau commented on src/alr/alr-commands-edit.adb
> +                  & TTY.Emph (Prj_Pattern)
You should add Root_Pattern here to.

2024-06-20 13:52 UTC, mosteo commented
Refactored common parts into `Alire.Environment.Formatting`, that already existed.

2024-06-20 16:38 UTC, Fabien-Chouteau approved these changes

2024-06-23 16:27 UTC, merged