fix: ability to pin a crate that 'provides' a dependency
alire-project/alire pull request #1771
Opened 2024-10-02 11:31 UTC by mosteo

This caused a crate mismatch before the fix.

Fixes https://github.com/alire-project/alire/issues/1693

2024-10-02 11:52 UTC, mosteo commented
@reznikmm give this one a shot if you can, for your use case.

2024-10-07 08:44 UTC, Fabien-Chouteau requested changes

2024-10-07 08:44 UTC, Fabien-Chouteau commented on src/alire/alire-roots.adb
> +   -- noteBuild --
Looks like a little mistake here.

2024-10-07 09:29 UTC, mosteo commented on src/alire/alire-roots.adb
> +   -- noteBuild --
Ooops indeed.

2024-10-07 11:30 UTC, Fabien-Chouteau approved these changes

2024-10-07 11:33 UTC, merged