Add support for git repos with multiple remotes configured
alire-project/alire pull request #1782
Opened 2024-10-14 12:28 UTC by Seb-MCaw

A Git repo may have multiple remotes configured, often with different branches tracking different remotes. For example, development may be done on a private repository, with release/production versions available on a public repository.

Currently Alire assumes there is at most one remote, and therefore ends up [using whichever is first alphabetically](https://github.com/alire-project/alire/blob/e20a5cbe0bb29c59c68361321c8e0bc04a81b377/src/alire/alire-vcss-git.adb#L416) when there is more than one. In practice, this is only relevant to `alr publish`ing, since dependencies are always fetched as a plain `git clone`, which does indeed yield a repo with only one remote.

This PR makes this assumption more explicit where applicable, and adds a subprogram to `Alire.Publish.Local_Repository` which attempts to guess the appropriate remote when there is more than one.

2024-10-14 15:20 UTC, Seb-MCaw commented
This is basically ready for review, but it's left as a draft because there is some minor overlap with #1736; I'll make a few more changes here if/when that one is merged.

2024-10-15 15:26 UTC, Seb-MCaw commented
This one is ready for review too, @mosteo. You can ignore my previous (deleted) comment.

2024-10-24 14:29 UTC, mosteo commented on testsuite/tests/publish/multiple-remotes/test.py
> +    return git_head()
Should this be in helpers.py named as `git_commit_file`, for general availability?

2024-10-24 14:42 UTC, mosteo requested changes
Just a minor refactor.

2024-10-28 13:24 UTC, Seb-MCaw commented
I'm assuming [this](https://github.com/alire-project/alire/actions/runs/11554342812/job/32157351611?pr=1782#step:17:1108) is transient.

2024-10-28 13:53 UTC, mosteo commented
> I'm assuming [this](https://github.com/alire-project/alire/actions/runs/11554342812/job/32157351611?pr=1782#step:17:1108) is transient.

Yes it is.

2024-10-29 06:05 UTC, mosteo approved these changes

2024-10-29 06:05 UTC, merged

2024-10-29 06:06 UTC, mosteo commented
Merged, thanks.