Alire.Utils.User_Input: add function to query user's name, email and GitHub login
alire-project/alire pull request #461
Opened 2020-07-01 14:34 UTC by Fabien-Chouteau

Can be used to implement #455.

2020-09-25 14:28 UTC, mosteo requested changes

2020-09-25 14:28 UTC, mosteo commented on src/alire/alire-utils-user_input.adb
> +                               Default    => "githib-username",
typo

2020-09-25 14:28 UTC, mosteo commented on src/alire/alire-utils-user_input.adb
> +                               Default    => "githib-username",
(in "githib-username")

2020-09-25 14:42 UTC, Fabien-Chouteau commented
Elaboration issue :(

Sorry I don't have time to investigate before the week-end.

2020-09-27 17:13 UTC, mosteo commented
Hi Fabien, I took a stab at fixing the circular elab, I hope you don't mind.

2020-09-28 08:22 UTC, Fabien-Chouteau commented
Thank you :+1:

2020-09-28 11:29 UTC, mosteo approved these changes

2020-09-28 11:29 UTC, merged