Pins to remote branches
alire-project/alire pull request #754
Opened 2021-06-21 12:30 UTC by mosteo

An enhancement on top of #743 and #751. Now you can do

```
[[pins]]
foo = { url="http://blah", branch="bar" }
```

2021-06-23 16:02 UTC, Fabien-Chouteau requested changes

2021-06-23 16:02 UTC, Fabien-Chouteau commented on src/alire/alire-user_pins.adb
> +         if not VCSs.Git.Handler.Update (Destination, Branch).Success then
Will this do a recursive update? (submodules)

2021-06-23 16:02 UTC, Fabien-Chouteau commented on testsuite/drivers/helpers.py
> +def touch(file):
E3 has a touch function: `from e3.os.fs import touch`, it should be available.

2021-06-23 16:11 UTC, mosteo commented on src/alire/alire-user_pins.adb
> +         if not VCSs.Git.Handler.Update (Destination, Branch).Success then
Yes, it's at https://github.com/alire-project/alire/blob/01264f9c9e1785ed19e04d41e9ef5598f2fc5123/src/alire/alire-vcss-git.adb#L436 and https://github.com/alire-project/alire/blob/01264f9c9e1785ed19e04d41e9ef5598f2fc5123/src/alire/alire-vcss-git.adb#L443

2021-06-23 16:12 UTC, mosteo commented on testsuite/drivers/helpers.py
> +def touch(file):
OK, I'll use that one then.

2021-06-23 16:33 UTC, mosteo commented on testsuite/drivers/helpers.py
> +def touch(file):
And I'll read through the `e3` APIs, I hadn't realized there were so many things there that can be useful.

2021-06-24 08:00 UTC, Fabien-Chouteau approved these changes

2021-06-25 09:28 UTC, merged