New command exec and support of aliases
alire-project/alire pull request #853
Opened 2021-09-16 12:18 UTC by Fabien-Chouteau

2021-09-17 07:46 UTC, mosteo requested changes
Nice feats, I'll have `alr list` back :-)

2021-09-17 07:46 UTC, mosteo commented on src/alr/alr-commands-exec.adb
> +      );
Copy-pain? :-)

2021-09-17 07:51 UTC, mosteo commented
An observation: from my testing it seems that once you define an alias, you cannot pass extra switches. For example, if `display` is an alias for `show`, running `alr display --graph` will ignore the switch. Would this make sense?

2021-09-17 08:42 UTC, Fabien-Chouteau commented on src/alr/alr-commands-exec.adb
> +      );
Indeed :man_facepalming:

2021-09-17 08:44 UTC, Fabien-Chouteau commented
> An observation: from my testing it seems that once you define an alias, you cannot pass extra switches. For example, if `display` is an alias for `show`, running `alr display --graph` will ignore the switch. Would this make sense?

It's not supposed to do that... I will check.

2021-09-17 08:50 UTC, Fabien-Chouteau commented
@mosteo 

It works on my side:
```console
$ alr config --set --global alias.display show
$ alr display --graph
# Synchronizing workspace...
Dependencies automatically updated as follows:  
[...]
Dependencies (graph):
                                      +-----------------------++-------------------+
```

2021-09-17 09:59 UTC, mosteo commented
Right you are... I messed something up in my previous attempt, sorry for the noise.

2021-09-28 15:03 UTC, Fabien-Chouteau commented
@mosteo I think I should introduce the `--` double-dash delimiter for `alr exec` and `alr build`.
In case we want options for these commands in the future, e.g.:
```console
$ alr build --mode=release -- -XTEST=plop -cargs -g # only "-XTEST=plop -cargs -g" is passed to gprbuild
```

what do you think?

2021-09-28 15:12 UTC, mosteo commented
Sounds very sensible

2021-09-28 15:12 UTC, onox commented
> @mosteo I think I should introduce the `--` double-dash delimiter for `alr exec` and `alr build`.

Would this help to allow global options be moved back to after the command? Having 1 place where the user can define global and command-specific options would be easier for users.

2021-09-28 15:43 UTC, Fabien-Chouteau commented
Global options would still have to be placed before the command. It's cleaner to separate the two in my opinion.

2021-09-30 15:12 UTC, mosteo approved these changes

2021-09-30 15:13 UTC, merged

2021-09-30 15:13 UTC, mosteo commented
Another great couple of features; thanks, Fabien.