Build profiles and switches system
alire-project/alire pull request #895
Opened 2021-12-09 17:20 UTC by Fabien-Chouteau

Implementation of RFC #888

2021-12-10 16:50 UTC, mosteo requested changes

2021-12-10 16:50 UTC, mosteo commented on src/alire/alire-toml_keys.ads
> +   Build_Switches : constant String := "build_switches";
I would keep on using dashes as with the other similar keys

2021-12-10 16:53 UTC, mosteo commented
If I understood the tests correctly, this is the version in which the switches themselves can only be overridden for the own crate, right? 

This is a great addition, thanks Fabien.

2021-12-13 14:20 UTC, Fabien-Chouteau commented
> If I understood the tests correctly, this is the version in which the switches themselves can only be overridden for the own crate, right?

Yes indeed. Also the switch to change the default build mode of the root crate is missing (right now it's development).

2021-12-13 15:51 UTC, mosteo approved these changes

2021-12-13 17:31 UTC, merged