Fix several typos in trace and output
alire-project/alire pull request #912
Opened 2022-01-15 23:15 UTC by jquorning

2022-01-16 17:56 UTC, mosteo requested changes

2022-01-16 17:56 UTC, mosteo commented on src/alr/alr-commands-toolchain.adb
> +              ("Default toolchain contains mixed-precedence tools");
Mistranslation of Spanish "procedencia". Either "provenance" or "origin" would work here.

2022-01-16 18:43 UTC, mosteo approved these changes

2022-01-16 18:46 UTC, mosteo commented
Hi @jquorning , do you mind rebasing this one to get rid of the conflicts? Since you know better the changes.

2022-01-16 19:19 UTC, jquorning commented
Looks like rebase is working, even though I am not quite sure what happens under my feet :-)

2022-01-17 08:17 UTC, mosteo approved these changes

2022-01-17 08:18 UTC, merged